# ansible connection details (should match packer image settings)
kali_user: "kali"
kail_password: "kali"
ansible_user: "vagrant"
ansible_password: "vagrant"
centos_user: "vagrant"
centos_password: "vagrant"
pfsense_user: "vagrant"
pfsense_password: "vagrant"
win_admin_user: "administrator"
win_admin_password: "myTempPassword123"

# settings for domain (used to configure pfsense)
lab_base_tld: "lan"
lab_base_name: "lab"
internal_domain: "{{ lab_base_name }}.{{ lab_base_tld }}"
win_netbios_domain: "{{ lab_base_name | upper }}"
win_ca_common_name: "{{ lab_base_name | upper }}-PKI"

# settings for ansible and splunk (not currently used)
splunk_password: "1-splunk-password"
ansible_awx_password: "1-ansible-password"
ansible_awx_pg_password: "1-awx-pg-password"
ansible_awx_secret_key: "1-awx-secret-key"

