# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs', disabled: true

  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-kali2020"
    virtualbox.vm.box = "file://builds/virtualbox-kali2020.box"
    virtualbox.vm.network :private_network, ip: "192.168.152.28"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
  end

  config.vm.define "vmware" do |vmware|
    vmware.vm.box = "file://builds/vmware-kali2020.box"
    vmware.vm.hostname = "kali"
    vmware.vm.network :private_network, ip: "192.168.152.28"

    config.vm.provider "vmware_desktop" do |v|
        v.vmx["name"] = "kali2020"
        v.vmx["memsize"] = "1024"
        v.vmx["ethernet0.pcislotnumber"] = "33"
        v.cpus = 1
        v.gui = true   
    end

    config.ssh.username = 'kali'
    config.ssh.password = 'kali'
  end
end
