# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs', disabled: true

  # check for default provider and provision accordingly
  if ENV['VAGRANT_DEFAULT_PROVIDER'] == 'virtualbox'
    config.vm.define "virtualbox" do |virtualbox|
        virtualbox.vm.hostname = "centos8"
        virtualbox.vm.box = "file://builds/virtualbox-centos8.box"
        virtualbox.vm.network :private_network, ip: "192.168.152.18"

        config.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        end

        config.vm.provision "shell", inline: "echo Hello, World"
    end
  elsif ENV['VAGRANT_DEFAULT_PROVIDER'] == 'vmware_desktop'
    config.vm.define "vmware" do |vmware|
        vmware.vm.box = "file://builds/vmware-centos8.box"
        vmware.vm.hostname = "centos8"
        #vmware.vm.network :private_network, ip: "192.168.152.18"

        config.vm.provider "vmware_desktop" do |v|
            v.vmx["name"] = "centos8"
            v.vmx["memsize"] = "1024"
            v.vmx["ethernet0.pcislotnumber"] = "33"
            v.cpus = 1
            v.memory = 1024
            v.gui = true   
        end

        config.ssh.username = 'vagrant'
        config.ssh.password = 'vagrant'
    end
  end
end
