---
  - hosts: all
    gather_facts: True
    pre_tasks:
      - name: Windows Variable
        include_vars: vars/windows.yml
        when: ansible_system == 'Win32NT'
    tasks:
      - name: Run sysprep
        win_shell: |
          # Prepare the custom unattend if it exists
          $windir = $env:windir
          $process = "$windir\system32\sysprep\sysprep.exe"
          $args = ""
          if(Test-Path "A:\unattend.xml"){
            $args = "/oobe /generalize /quiet /mode:vm /unattend:a:\unattend.xml"
          }else{
            $args = "/oobe /generalize /quiet /mode:vm"
          }
          start-process -wait $process $args
        register: script_result

      - name: Script result
        debug: 
          msg:
            - "{{ script_result }}"


          